### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Poltergeist-ix** [Poltergeistzx/pz-translate-zx#1]
List of known issues that need improvement.

- [x] add support for Map translation (map.info, title, description)
- [ ] add support for RadioData_%%
- [x] add support for concat between translation lines
- [x] add import feature
- [ ] add other modes without auto trnslations
- [ ] populate translation lines from files where possible, e.g. item & recipe scripts
- [ ] improve protection for tags. e.g. `%1`, `\n`, `<br>`, etc...
- [ ] resolve possible issues with translator
